productWalletCreateV1:
  handler: functions/create.v1
  events:
    - http:
        path: v1/create
        method: post
        cors: true

productWalletUpdateV1:
  handler: functions/update.v1
  events:
    - http:
        path: v1/update
        method: put
        cors: true

productWalletFindV1:
  handler: functions/find.v1
  events:
    - http:
        path: v1/find
        method: post
        cors: true

productWalletFetchV1:
  handler: functions/fetch.v1
  events:
    - http:
        path: v1/fetch
        method: post
        cors: true
